name       : webtorrent-desktop
version    : 0.21.0
release    : 7
source     :
    - https://github.com/webtorrent/webtorrent-desktop/archive/v0.21.0.tar.gz : 6a622ae14a7424604b8a94402156bfdd4b1debf9fe4e6db852f38061910febd4
license    : MIT
component  : multimedia.video
networking : yes
summary    : Cross platform streaming torrent app
description: |
    Webtorrent allows you to stream torrent files sequentially and watch them as you download, rather than downloading first, and then watching the files.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xi)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - nodejs
    - git
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run package linux
install    : |
    install -Dm00644 $workdir/static/WebTorrent.png $installdir/usr/share/pixmaps/webtorrent-desktop.png
    install -Dm00644 $pkgfiles/webtorrent-desktop.desktop $installdir/usr/share/applications/webtorrent-desktop.desktop

    install -dm00755 $installdir/usr/share/webtorrent-desktop
    cp -r $workdir/dist/WebTorrent-linux-x64/* $installdir/usr/share/webtorrent-desktop/

    install -dm00755 $installdir/usr/bin/
    ln -sv /usr/share/webtorrent-desktop/WebTorrent $installdir/usr/bin/webtorrent-desktop
