name       : webtorrent-desktop
version    : 0.20.0
release    : 4
source     :
    - https://github.com/webtorrent/webtorrent-desktop/archive/v0.20.0.tar.gz : 2eec644337f2e8a47187c54d702491e3b4c1f1236dae48cb494c4e99ba0a9796
license    : MIT
component  : multimedia.video
networking : yes
summary    : Cross platform streaming torrent app
description: |
    Webtorrent allows you to stream torrent files sequentially and watch them as you download, rather than downloading first, and then watching the files.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xi)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-solbuild-fixes.patch
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run package linux
install    : |
    install -Dm00644 $workdir/static/WebTorrent.png $installdir/usr/share/pixmaps/webtorrent-desktop.png
    install -Dm00644 $pkgfiles/webtorrent-desktop.desktop $installdir/usr/share/applications/webtorrent-desktop.desktop

    install -dm00755 $installdir/usr/share/webtorrent-desktop
    cp -r $workdir/dist/WebTorrent-linux-x64/* $installdir/usr/share/webtorrent-desktop/

    install -dm00755 $installdir/usr/bin/
    ln -sv /usr/share/webtorrent-desktop/WebTorrent $installdir/usr/bin/webtorrent-desktop
