name       : webtorrent-desktop
version    : 0.18.0
release    : 1
source     :
    - https://github.com/webtorrent/webtorrent-desktop/archive/v0.18.0.tar.gz : 25b92aab9cc6d076715a12bdaeae950f6885da19d87948a6acf007ba246b9494
license    : MIT
component  : multimedia.video
networking : yes
summary    : Cross platform streaming torrent app
description: |
    Webtorrent allows you to stream torrent files sequentially and watch them as you download, rather than downloading first, and then watching the files.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-solbuild-fixes.patch
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run package linux
install    : |
    install -Dm644 $workdir/static/WebTorrent.png $installdir/usr/share/pixmaps/webtorrent-desktop.png
    install -Dm644 $pkgfiles/webtorrent-desktop.desktop $installdir/usr/share/applications/webtorrent-desktop.desktop

    install -dm755 $installdir/usr/share/webtorrent-desktop
    cp -r $workdir/dist/WebTorrent-linux-x64/* $installdir/usr/share/webtorrent-desktop/

    install -dm755 $installdir/usr/bin/
    ln -sv /usr/share/webtorrent-desktop/WebTorrent $installdir/usr/bin/webtorrent-desktop


